### ISSUE TITLE
Incorrect representation of permissions

### ISSUE THREAD

**Issue by KHIT93** [RachidLaasri/LaravelInstaller#1]
The PermissionsChecker returns error if a path has more permissions than required.
Fx. storage/logs/ has 0777 as the permission, which means read+write+exec for all.
But in config/requirements.php it is configured for permission 0775, which is what is required to remove the error.
It would be more correct if it would only return error if an item in the permissions array had less permissions that required. Fx. 0644 where 0775 is required.

Can be reproduced on any linux based webserver that is not opened as the current user (prebuilt LAMP stack). Tested with Arch/Manjaro Linux and Debian 7.6

**Comment by RachidLaasri** [comment]
Thanks for talking time to write this issue. 

I am not quite i understand what you meant, correct me if i am wrong but this :

```
if(!($this->getPermission($folder) == $permission))
```
Should be : 
```
if(!($this->getPermission($folder) >= $permission))
```
I am waiting for your feedback so i can update the class.

Thank you.

**Comment by KHIT93** [comment]
I can confirm that the change is working in both test systems.

**Comment by RachidLaasri** [comment]
Fixed.

Thank you.
