### ISSUE TITLE
Portuguese Language

### ISSUE THREAD

**Issue by oliveiraped** [RachidLaasri/LaravelInstaller#10]
<?php

/* Translate made By Pedro Oliveira www.reportula.org */

return [

    /**
     *
     * Shared translations.
     *
     */
    'title' => 'Instalador Laravel',
    'next' => 'Seguinte',

    /**
     *
     * Home page translations.
     *
     */
    'welcome' => [
        'title'   => 'Bem Vindo ao Instalador...',
        'message' => 'Bem Vindo ao Wizard do Instalador.',
    ],

    /**
     *
     * Requirements page translations.
     *
     */
    'requirements' => [
        'title' => 'Requisitos',
    ],

    /**
     *
     * Permissions page translations.
     *
     */
    'permissions' => [
        'title' => 'Permissões',
    ],

    /**
     *
     * Environment page translations.
     *
     */
    'environment' => [
        'title' => 'Configurações do Ambiente',
        'save' => 'Guardar.env',
        'success' => 'Suas configurações de arquivo .env foram salvas.',
        'errors' => 'Não foi possível salvar o arquivo .env, por favor, criá-lo manualmente.',
    ],

    /**
     *
     * upgrade welcome page translations.
     *
     */
    'upgrade' => [
        'title' => 'Atualizar Aplicação',
        'welcome' => 'Atualmente em execução a versão: e a versão mais recente disponível é: mais recente clique para atualizar.',
        'button' => 'Atualizar',
    ],

    /**
     *
     * Final page translations.
     *
     */
    'final' => [
        'title' => 'Terminado',
        'finished' => 'Aplicação foi instalado com êxito.',
        'exit' => 'Clique aqui para sair',
    ],
];

**Comment by RachidLaasri** [comment]
Hi, 

Can you please create a pull request instead? Thanks!
