### ISSUE TITLE
Don't publish vendor assets or generate key at runFinal()

### ISSUE THREAD

**Issue by elnurxf** [RachidLaasri/LaravelInstaller#100]
I propose to add to config options to turn on/off generateKey() and publishVendorAssets() methods.
Since I'm using only English locale and don't want to have all locales at least. Besides all other non-required files from other vendors will be published with no reason and request.

Also generating again app key not an good idea, Let say I've pase my pre-defined .ENV file with specified key, but installer will overwrite my APP_KEY without asking me for that.

So, my proposal is to add to config installer.php:

'installed'              => [
        'publishVendor'  => false,
        'generateKey'        => false,
        .....
]

**Comment by Tropicalista** [comment]
I agree. Please add this.

**Comment by TechTailor** [comment]
I need to look at the code again, but I don't think it was running generateKey command anyways. From what I remember, the app key is hardcoded (which you can modify to the one you are using and I will just add that to the ENV file).
