### ISSUE TITLE
Support for Laravel 5.5

### ISSUE THREAD

**Issue by rattfieldnz** [RachidLaasri/LaravelInstaller#101]
Hi Rachid,

First of all, I really appreciate how useful your package has been for my projects :). 

I am wondering what support for Laravel 5.5 compatibility there is with this package? I am working on a yet-to-be-released project, which I have recently made fully compatible with Laravel 5.5.

This is not an issue per se - rather, just a question :).

Cheers!

Rob

**Comment by RachidLaasri** [comment]
It does support Laravel 5.5
