### ISSUE TITLE
.env form

### ISSUE THREAD

**Issue by danilodorgam** [RachidLaasri/LaravelInstaller#104]
What data source does it use to assemble the .env fill form?
![04-09-2017 11-32-28](https://user-images.githubusercontent.com/3344991/30030683-cd3a4ce0-9164-11e7-948c-a2e481836bb6.png)
I wanted to add more fields

**Comment by RachidLaasri** [comment]
It reads the .env file. https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/Helpers/EnvironmentManager.php#L25
