### ISSUE TITLE
ErrorException checkPHPversion()

### ISSUE THREAD

**Issue by harpreet9629** [RachidLaasri/LaravelInstaller#113]
I have this issue when i click on check requirements

Argument 1 passed to RachidLaasri\LaravelInstaller\Helpers\RequirementsChecker::checkPHPversion() must be an instance of RachidLaasri\LaravelInstaller\Helpers\string, string given, called in /home/socialdashboard/public_html/vendor/rachidlaasri/laravel-installer/src/Controllers/RequirementsController.php on line 32 and defined

**Comment by ellyirungu** [comment]
hey harpreet,  inside RequirementsController , remove pass no value by removing config('installer.core.minPhpVersion')   which is under requirements()....so 
your new function should be 
    public function requirements()
    {
        $phpSupportInfo = $this->requirements->checkPHPversion(
           // config('installer.core.minPhpVersion')

        );


        $requirements = $this->requirements->check(
            
        );

        return view('vendor.installer.requirements', compact('requirements', 'phpSupportInfo'));
    }

**Comment by ellyirungu** [comment]
hey harpreet, inside RequirementsController , remove pass no value by removing config('installer.core.minPhpVersion') which is under requirements()....so
your new function should be


    public function requirements()
    {
        $phpSupportInfo = $this->requirements->checkPHPversion(
          

        );


        $requirements = $this->requirements->check(
            config('installer.requirements')
        );

        return view('vendor.installer.requirements', compact('requirements', 'phpSupportInfo'));
    }
