### ISSUE TITLE
ErrorException: Database setting up error

### ISSUE THREAD

**Issue by daoanhvuacc** [RachidLaasri/LaravelInstaller#114]
`Missing argument 3 for RachidLaasri\LaravelInstaller\Helpers\DatabaseManager::response(),`
<img width="688" alt="screen shot 2017-09-19 at 17 20 20" src="https://user-images.githubusercontent.com/8165254/30587982-4317d5d0-9d5f-11e7-91ac-989ff1da8dc1.png">

**Comment by salihkiraz** [comment]
try https://github.com/RachidLaasri/LaravelInstaller/pull/115

**Comment by vinsbg** [comment]
Same issue here, #115 not working.
