### ISSUE TITLE
Route [LaravelInstaller::environmentSave] not defined.

### ISSUE THREAD

**Issue by closer01** [RachidLaasri/LaravelInstaller#118]
Hi, I have updated LaravelInstaller from 1.5 to 3.0 with composer. 
When i go to http://localhost/site/install/ it shows installer , but when i click to Next button i receive this error : 
```
ErrorException in UrlGenerator.php line 304:
Route [LaravelInstaller::environmentSave] not defined. (View: C:\xampp\htdocs\site\resources\views\vendor\installer\environment.blade.php)
```
How to fix it ?

**Comment by Tropicalista** [comment]
same problem here

**Comment by masroore** [comment]
Remove your old `resource/view/vendor/installer` folder as well as `config/installer.php` file.
Then `artisan vendor:publish` to publish the required items
