### ISSUE TITLE
Missing argument 3...DatabaseManager.php on line 59 and defined

### ISSUE THREAD

**Issue by zhsolutions** [RachidLaasri/LaravelInstaller#120]
I have already tried fix 115, did not work.

**Comment by thanhbop** [comment]
How to fix it???
Thanks
Missing argument 3 for RachidLaasri\LaravelInstaller\Helpers\DatabaseManager::response(), called in E:\wamp64\www\laravel\2\vendor\rachidlaasri\laravel-installer\src\Helpers\DatabaseManager.php on line 59 and defined

**Comment by jeremykenedy** [comment]
These errors were introduced with PR https://github.com/RachidLaasri/LaravelInstaller/pull/109

**Comment by TechTailor** [comment]
I realized that when I attempted to install on my localhost where my db user root didnt have a password it kept failing. However the bigger issue that most people maybe facing is with redis. Not many use it out of the box and as such don't really think of configuring it and end up with this issue.

**Comment by jeremykenedy** [comment]
those are solid fixes you suggested

**Comment by laravelbap** [comment]
I had the same problem. After checking source. It turned out that I did not have the DatabaseSeeder file that is required. Adding DatabaseSeeder fixed my problem.
