### ISSUE TITLE
Error in LaravelInstallerServiceProvider

### ISSUE THREAD

**Issue by pishcheiyko** [RachidLaasri/LaravelInstaller#121]
I install Laravel 5.5* and your package v. ^3.0
When I executed publish command 
**php artisan vendor:publish --tag=laravelinstaller** 
I get error 
Uncaught ErrorException: require(/routes/web.php): failed to open stream: No such file or directory in /home/alex/webserver/laravel/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:71

This error occurs because you are using **routes**
$this->loadRoutesFrom(__DIR__.'/../routes/web.php'); 
instead **Routes**
$this->loadRoutesFrom(__DIR__.'/../Routes/web.php');

I fixed it and command has been completed

**Comment by stephenlake** [comment]
@RachidLaasri Unit tests mate.

**Comment by twf-nikhila** [comment]
@pishcheiyko :+1:  Great that fixed.

**Comment by RachidLaasri** [comment]
Fixed.
