### ISSUE TITLE
When install laravel has error??

### ISSUE THREAD

**Issue by thanhbop** [RachidLaasri/LaravelInstaller#125]
Missing argument 3 for RachidLaasri\LaravelInstaller\Helpers\DatabaseManager::response(), called in E:\wamp64\www\laravel\2\vendor\rachidlaasri\laravel-installer\src\Helpers\DatabaseManager.php on line 59 and defined

**Comment by TechTailor** [comment]
Kindly refer to Issue #120. I have posted a possible solution to fix and run this without issues.
