### ISSUE TITLE
get admin info

### ISSUE THREAD

**Issue by robertnicjoo** [RachidLaasri/LaravelInstaller#128]
Hi,

As this package gets all migrations setup how can i add admin info in users table? as example wordpress gets info of admin while setup process and after setup is finished 1 user as admin is exist in database?

thanks.

**Comment by TechTailor** [comment]
The package should automatically seed any data you have set.

Look into the 'database/seeds' folders in your app & check out database seeding on the laravel support page, you will get details of how to add seeds for the db. That way you can add a default admin account.

-TT

**Comment by robertnicjoo** [comment]
@TechTailor So what you say is basically make static user instead of dynamic with users info, lets assume that's the good way and we agree with that, don't you think that installer should run `php artisan make:auth` in order to user can login after finishes installing?

**Comment by TechTailor** [comment]
The Installer is designed to distribute a completed project to say, a client. As such it shouldn't run any commands that may overwrite any controllers or views that's already been finalized. This installer does what most other apps have, ability to setup and seed an initial admin account (that the user can modify later on).

After the initial setup, the installer isn't accessible and the user can access the app with the admin credentials which you seeded and then modify it. 

The usage of this package is "after" the development of your app is complete and you intend to distribute it to someone who isn't very familiar with backend code or to a generic user who you don't want messing with the files.

Hope this clears up.

-TT
