### ISSUE TITLE
routes

### ISSUE THREAD

**Issue by robertnicjoo** [RachidLaasri/LaravelInstaller#129]
Hi,

Do I have to add routes manually? because when i visit `domain.dev/install` this is what i get

```
404 Not Found
nginx/1.12.0
```

If yes please share routes so i can use it.

Thanks.

**Comment by TechTailor** [comment]
Did you follow the installation instructions thoroughly? Especially the "artisan vendor publish" command? Also are you using Laravel 5.5 or a previous version?

**Comment by robertnicjoo** [comment]
@TechTailor yes i did but somehow it didn't work till i restart my system, now everything is working.
thanks.
