### ISSUE TITLE
Too few arguments to function RachidLaasri\LaravelInstaller\Helpers\DatabaseManager::response()

### ISSUE THREAD

**Issue by FrozenHeartFD** [RachidLaasri/LaravelInstaller#139]
Type error: Too few arguments to function RachidLaasri\LaravelInstaller\Helpers\DatabaseManager::response(), 1 passed in C:\xampp\htdocs\potty\vendor\rachidlaasri\laravel-installer\src\Helpers\DatabaseManager.php on line 40 and exactly 3 expected

**Comment by redhawk07** [comment]
Already solved with #137 
A new release would be good. I also had this problem. The composer pulls the latest release (3.2.0), where the changes are not yet included.

**Comment by RachidLaasri** [comment]
Please try now.
