### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by poriia** [RachidLaasri/LaravelInstaller#140]
FatalThrowableError in ...\vendor\rachidlaasri\laravel-installer\src\Helpers\FinalInstallManager.php line 38:
Using $this when not in object context

**Comment by agungjk** [comment]
@ #123

**Comment by RachidLaasri** [comment]
Fixed https://github.com/RachidLaasri/LaravelInstaller/commit/09ae107328c7893a1f64134c60a7c040b9daff20
