### ISSUE TITLE
Adding custom configs to the .env file?

### ISSUE THREAD

**Issue by crysfel** [RachidLaasri/LaravelInstaller#143]
Thanks for the great work!!

In my current laravel project, I have several custom configurations in the .env file. I'm wondering how can I add those fields to the wizard form? is it also possible to execute additional artisan tasks?

Thanks!

**Comment by RachidLaasri** [comment]
Have you tried adding them to .env.example file?

**Comment by joveice** [comment]
This could be implemented using the #142 etc add custom validators to the config file, then add the forms manually in the views. then it would pass the data to the writer that then can place values to the .env file.

**Comment by Dob6458** [comment]
Good project

**Comment by RachidLaasri** [comment]
I am closing this because it seems inactive. If you still facing the same issue, feel free to reopen it.

Thank you.
