### ISSUE TITLE
Undefined method loadRoutesFrom on Laravel 5.2

### ISSUE THREAD

**Issue by baig772** [RachidLaasri/LaravelInstaller#152]
I was having the same issue on Laravel5.2 and I fixed it by by adding 
`use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;` in LaravelInstallerServiceProvder.php
Please make an update or let me know if this has already been fixed?

**Comment by RachidLaasri** [comment]
I am closing this because it seems inactive. If you still facing the same issue, feel free to reopen it.

Thank you.
