### ISSUE TITLE
need minor change on readme

### ISSUE THREAD

**Issue by milocosmopolitan** [RachidLaasri/LaravelInstaller#17]
need some change

app/config/app.php

to

config/app.php

&

php artisan vendor:publish --provider=RachidLaasri\LaravelInstaller\Providers\LaravelInstallerServiceProvider

to

php artisan vendor:publish --provider="RachidLaasri\LaravelInstaller\Providers\LaravelInstallerServiceProvider"

**Comment by RachidLaasri** [comment]
Fixed, Thanks!
