### ISSUE TITLE
Register middleware from service provider

### ISSUE THREAD

**Issue by Tropicalista** [RachidLaasri/LaravelInstaller#2]
This is not an issue, but more a suggestion. Why not register the route middlewar directly from service provider? Something like this could work:

    app('router')->middleware('isInstalled', '\RachidLaasri\LaravelInstaller\Middleware\IsInstalled');

**Comment by RachidLaasri** [comment]
Hi,

This is possible, but, i see no benefits of changing it since the current one works perfectly.

**Comment by Tropicalista** [comment]
Yes the package is working great, is just to avoid to add manually the middleware. :)

**Comment by RachidLaasri** [comment]
Yes, i understand.

I will definitely add that in the next update.

Thank you.

**Comment by RachidLaasri** [comment]
https://github.com/RachidLaasri/LaravelInstaller/commit/112e8d5ca0d75fa5f0bc52c17705fcbf072b5c40
