### ISSUE TITLE
Laravel Installer Video

### ISSUE THREAD

**Issue by tnylea** [RachidLaasri/LaravelInstaller#21]
Hey There :) Wasn't sure where to post this at, so I thought I would post it here. I've created a screencast of this package here: https://www.youtube.com/watch?v=Jput5doFYLg

You can include the link or embed the video in the Readme if you would like :)

Great Package! Thank you.

**Comment by RachidLaasri** [comment]
Hi,

Thanks for the screencast, I tweeted it before and posted it here couple days ago.

I will definitely link to it.
