### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by lukacavic** [RachidLaasri/LaravelInstaller#23]
Installer is awesome, how about making upgrade app to?

**Comment by RachidLaasri** [comment]
Any suggestions on how would that work?

**Comment by lukacavic** [comment]
1) Application has version number in some config
2) Installer checks for version of app in config and on custom location (etc . http://www.myproject.com/updates/version.json) where is new version and compares them
3) If there is new version of app on custom location:
- installer makes .zip of local app and database backup
- installer downloads .zip of updated app, extracts it and overwrites local application
- Installer runs migrations and seeds if any
- Installer updates config with new version
4) If errors occured with update there is local backup of database and application that can be restored

Something like that :)

**Comment by tamaghna91** [comment]
Problem starts rolling in Laravel 5.2

**Comment by RachidLaasri** [comment]
What problem?
