### ISSUE TITLE
Can installer create folder and set to them permission?

### ISSUE THREAD

**Issue by stojankukrika** [RachidLaasri/LaravelInstaller#24]
Hi,
I wont to thank you for that great package. 

I have only one question : can installer create folder and set to them permission? I see that he can check permission on some folder but I didn't find that he can create some folder during install process.

**Comment by RachidLaasri** [comment]
Hi,

I will look into that.

**Comment by stojankukrika** [comment]
tnx

**Comment by stojankukrika** [comment]
any progress about that?

**Comment by stojankukrika** [comment]
any progress about that?

**Comment by stojankukrika** [comment]
I finish in my way.TNX
