### ISSUE TITLE
Input Fields Instead of Textarea

### ISSUE THREAD

**Issue by shammadahmed** [RachidLaasri/LaravelInstaller#26]
Can the installer have input fields for entering the database details instead of the whole textarea giving the .env file?

**Comment by RachidLaasri** [comment]
Yes, it can be done by splitting the .env file lines and put each one of them in its own input and then merge the content and put it back in the .env file.

**Comment by Amaxila** [comment]
Maybe also generate the application key in the step and also set the APP_DEBUG to false.

**Comment by renztoygwapo** [comment]
yes, I 2nd the motion, want to see some improvements in next release.
Anyway thanks for the web installer it's working good in laravel 5.3.

**Comment by ajayfroiden** [comment]
You can use the forked version for laravel 5.4. I has input fields instead of textarea.
 https://github.com/Froiden/laravel-installer

**Comment by jeremykenedy** [comment]
These have been added the proper Laravel way in https://github.com/RachidLaasri/LaravelInstaller/pull/89.

**Comment by jeremykenedy** [comment]
@RachidLaasri I think this can be closed.
