### ISSUE TITLE
How can i migrate vendor migration?

### ISSUE THREAD

**Issue by tirjok** [RachidLaasri/LaravelInstaller#28]
Hi,
Thanks for your awesome package. One question : How can i migrate vendo database migration.

/Tirjok

**Comment by RachidLaasri** [comment]
Hi,

Can you explain more?

**Comment by tirjok** [comment]
Yah, Such as i want to run below migrations while installing

php artisan migrate --path=vendor/genealabs/laravel-governor/database/migrations

**Comment by shammadahmed** [comment]
Add this to the final controller:

`Artisan::call('php artisan migrate --path=vendor/genealabs/laravel-governor/database/migrations);`
