### ISSUE TITLE
Can't locate path: </srv/www/peeps.gwaz.dev/vendor/rachidlaasri/laravel-installer/src/Providers/../views>

### ISSUE THREAD

**Issue by mattzuba** [RachidLaasri/LaravelInstaller#3]
the publishFiles() method in the Service Provider is trying to publish __DIR__.'/../views' with a lowercase v, rather than Views with a capital V.

**Comment by RachidLaasri** [comment]
Thanks for reporting this issue.
It is fixed now : https://github.com/RachidLaasri/LaravelInstaller/commit/154d5141d8aa603346e131a3b57b1614a5d6b210
