### ISSUE TITLE
Error installing on Laravel 5.0

### ISSUE THREAD

**Issue by trallamochila** [RachidLaasri/LaravelInstaller#37]
PHP 5.5.9
Laravel 5.0

I pull the package through Composer, and run composer update. 

This is the output:

...
Generating autoload files
> php artisan clear-compiled

                       
**  [ErrorException]     
  Illegal offset type  **
                       

Script php artisan clear-compiled handling the post-update-cmd event returned with an error

                      
**  [RuntimeException]  
  Error Output:     **  
                      
...

**Comment by RachidLaasri** [comment]
I believe that this has nothing to do with the package.

Give this a look https://laracasts.com/discuss/channels/general-discussion/script-php-artisan-clear-compiled-handling-the-post-cmd-update-event-returned-with-an-error-laravel-5016
