### ISSUE TITLE
NotFoundHttpException in Application.php line 902:

### ISSUE THREAD

**Issue by oleghalin** [RachidLaasri/LaravelInstaller#38]
NotFoundHttpException in Application.php line 902:

First time was okay, but after first time installation i have this error. What can be wrong?

**Comment by RachidLaasri** [comment]
Hi,

It's normal that you cannot install it twice. Once you finish the installation you can not access /install anymore.

If you want to re-install it again, you have to drop all the tables.

**Comment by oleghalin** [comment]
Rollback migrations?

**Comment by RachidLaasri** [comment]
Yes.

**Comment by oleghalin** [comment]
i have empty database.

**Comment by RachidLaasri** [comment]
Try to reinstall it now.

**Comment by oleghalin** [comment]
Nope. Same error. 
![image](https://cloud.githubusercontent.com/assets/9086983/14786362/338768d8-0b07-11e6-9fc9-68524cd9ef13.png)

**Comment by oleghalin** [comment]
Can u help me? I havent same error.

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/14884696/3e14b52c-0d4f-11e6-9aa3-bd45af86cf12.png)

**Comment by oleghalin** [comment]
installed in storage must be deleted too.
