### ISSUE TITLE
Class \RachidLaasri\LaravelInstaller\Middleware\IsInstalled does not exist

### ISSUE THREAD

**Issue by mattzuba** [RachidLaasri/LaravelInstaller#4]
Change made in Issue #2 used a capital I on IsInstalled, rather than a lowercase i.

**Comment by RachidLaasri** [comment]
Thanks for reporting this issue.
It is fixed now : https://github.com/RachidLaasri/LaravelInstaller/commit/4e2fbd414f090922c463060f6197a70c761e359a
