### ISSUE TITLE
Question: auto-remove itself?

### ISSUE THREAD

**Issue by KuenzelIT** [RachidLaasri/LaravelInstaller#40]
Hey,

does the installer automatically removes itself after the installation?

Sounds like an awesome package!

**Comment by RachidLaasri** [comment]
Yes, the package detects if the app is already install and throws 404 error.

**Comment by TechnikEmpire** [comment]
@RachidLaasri So, with that information, how does one undo the installer process? I tested the installer, it failed with an error, but now it's giving 404 etc.
