### ISSUE TITLE
It works on first time then it throws errors

### ISSUE THREAD

**Issue by iftikharuddin** [RachidLaasri/LaravelInstaller#45]
I tried to install this Web Installer on my App, it worked perfectly but again when i tried to access /install route it redirect me to 404 but then i saw a middle ware in your package (canInstall) . I changed that to go on even if it is already installed . But when i hit save .env it doesn't work and hangs on this route http://site.com/install/environment

**Comment by RachidLaasri** [comment]
Of course the install route should not be accessible after the installation. That's the normal behavior.

**Comment by iftikharuddin** [comment]
But what if i want to deploy it into online server from localhost, and then do installation via that route? Or what if i want to send it to client ?

**Comment by RachidLaasri** [comment]
Then just remove the file? Or add it to your .gitignore?

**Comment by iftikharuddin** [comment]
@RachidLaasri  which one file i am confused here ?

**Comment by RachidLaasri** [comment]
A file named "installed" will be created inside the storage folder.

You can add that to your .gitignore.

**Comment by iftikharuddin** [comment]
i will give a try thanks
