### ISSUE TITLE
Remove middleware registration from boot method

### ISSUE THREAD

**Issue by mattzuba** [RachidLaasri/LaravelInstaller#5]
Once I started playing a little more with this this morning, the isInstalled middleware will not work when using the Sql Server DB engine, as no 'Show tables' SQL call exists, so the middleware fails.  I think it'd be better to revert back to including it in the instructions and maybe adding a note that if you are using something other than MySQL, a custom 'isInstalled' middleware will need to be used instead.

Thanks for your work on this thus far, it took me forever to finally find it, as no one in the irc chat could comprehend that I want to build an application to be installed by end users and needed an installer.

**Comment by RachidLaasri** [comment]
What is the best way to solve this in your opinion? I am thinking of one of these : 
1 - Delete the middleware and tell the end user to delete the installer folder manually.
2 - Add an if condition to the middleware class to determine if the client is using SQL SERVER and run a different SQL query to show tables.

**Comment by mattzuba** [comment]
Well I like the middleware, I think it's a good idea to have in there as a failsafe.  Providing the default like you have for MySQL will probably work for 99% of people using it.  I don't know if SHOW TABLES will work for Sqlite either though, so option 2 may cause someone else to submit a similar issue in the future.  

For me, I just added a call to overwrite the middleware in the boot method of a service provider that loads after the one from this package.  That may also a possible solution that could be mentioned in the README.  Just override the middleware if needed.

**Comment by RachidLaasri** [comment]
Yeah, that's one solution to go about it. 

I think i may just leave it that way since most of us are using MySQL and i will add a note in the README file so people can override the default middleware when needed.
