### ISSUE TITLE
newbie

### ISSUE THREAD

**Issue by rin1015** [RachidLaasri/LaravelInstaller#51]
hey Rachid
can i ask for the tutorial for this installation?
https://github.com/rin1015/animecenter

**Comment by RachidLaasri** [comment]
There's already a tutorial for that here: https://github.com/rin1015/animecenter#setup

**Comment by VictorAvelar** [comment]
Is it compatible with version 5.3 of the framework? Cheers!

**Comment by RachidLaasri** [comment]
Haven't tested it yet. But ti should work.
