### ISSUE TITLE
Request: New Release

### ISSUE THREAD

**Issue by shawndibble** [RachidLaasri/LaravelInstaller#57]
Currently, I have a number of tools that scan and analyze my application. One of the warnings I am getting is because I am using the dev-master instead of a version number.

Request: Can you release a new version number in github of your installer application?

**Comment by RachidLaasri** [comment]
Done, you can now pull the 1.5 version which contains the latest changes.

https://github.com/RachidLaasri/LaravelInstaller/releases/tag/1.5
