### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by edno** [RachidLaasri/LaravelInstaller#58]
Hi,

Thanks for this great package, I am currently implementing it for one of my Laravel 5 app.

Here a couple of suggestions for improvements:
- OR clause `|` for requirements. For example `mysql|pgsql`, if one of extensions is present then requirement is satisfied
- Optional clause `?` for requirements. For example `mysql?`, if extension is not present then a notification is raised, but the installation can continue
- `messages.php` should be `installer.php`
- middleware `canInstall` should redirect to `root` rather `404` (or at leat this should be a configurable)
- `DatabaseManager` is calling `migrate`, but would be better to call `migrate:refresh` this would allow to perform reinstall just by removing the file `installed`
- Non-minified CSS will help to do some customization

I'll try to push some PR for these improvements in the following days (weeks?).

**Comment by RachidLaasri** [comment]
Those are some really good suggestions, I'll try to implement them. Also, feel free to submit any PRs.

**Comment by jeremykenedy** [comment]
Most of these suggestions have been implemented in https://github.com/RachidLaasri/LaravelInstaller/pull/89
or at least the plugs are there for them to finish out the different migration options.

**Comment by jeremykenedy** [comment]
@edno The middleware request has been addressed in https://github.com/RachidLaasri/LaravelInstaller/pull/90
