### ISSUE TITLE
update option

### ISSUE THREAD

**Issue by lorvent** [RachidLaasri/LaravelInstaller#6]
after installation, if we provides a new version which requires modifying database

then we should be able to present updater screen to users.

please add this option aswell

**Comment by RachidLaasri** [comment]
Any suggestions of how would that work?

I am thinking about adding a new "Update" button to the database installer page, that way you can click on either "Install" or "Update",  The update button will just run :

- php artisan migrate:rollback
- php artisan migrate

Any other suggestions?

**Comment by lorvent** [comment]
may be in confid we should define any no. of updates (like every update may need some database stuff to be added/modifed)
and installer should add a database table which will maintain how many updates already installed (v1, v1.1, v1.2 etc) so that it can run migrations for remaining

also support for seeding a particular class (running php artisan db:seed will give bad results)

**Comment by RachidLaasri** [comment]
I will add an option to the config array `last_version => 2.3` and the installer will create a table `installer_versions(id, element, value)` and a record of `1, current_version, 1.0`.

And on the "Database installer page" it will check if the `current_version` is less than the `last_version` and display the update button.

For the seeding, i will add an array to the config file, if it is empty it will run `db:seed`, if the array is not empty it will loop through the array and run `db:seed` for each class.

Is that good?

**Comment by lorvent** [comment]
Yes....that sounds great and it fulfills the requirements.

thanks.

**Comment by RachidLaasri** [comment]
Perfect, I will do an update very soon.

**Comment by lorvent** [comment]
Thanks, I will keep an eye on it.

Also... post about this package to reddit.com/r/php and reditt.com/r/laravel after adding this feature, it will give good exposure.

**Comment by RachidLaasri** [comment]
This is possible now with new version.

**Comment by lorvent** [comment]
Thanks for the update

but i am afraid, its not proper way

for example: we have released 1.0.1, 1.0.2, 1.0.3
user missed first two and directly updating to 1.0.3

then how it is going to check what version user has?

we should check in database for user installed version and compare with current version (wordpress does this way https://github.com/WordPress/WordPress/blob/master/wp-includes/version.php contains version number and checks with DB then updates)

**Comment by RachidLaasri** [comment]
We also check if the user is already installed the application and the current running version is < than the latest version, after installation a file gets stored in storage folder contains the current running version so when you create a new version and you want them to update simply add the latest version number to your `installer.php` config file.

**Comment by lorvent** [comment]
but how does it handle migrations, seeds for each and every version?

for example, with each version we are providing some new features so migrations, seeds are needed like below
````
1.0.1 : ['migrations` => 'Blogmigration', `seeds` => 'BlogSeeder'],
1.0.2 : [`migrations` => 'TodoMigration', `seeds` => 'TodoSeeder'],
1.0.3 : [`igrations` => 'ArticleMigration', `seeds` => 'ArticleSeeder']
````

now, lets assume user already updated to 1.0.1 but missed 1.0.2
and now updating directly to 1.0.3

in such case, will it run migrations,seeds of both 1.0.2 and 1.0.3?

**Comment by RachidLaasri** [comment]
I got your point.

Looping through the array of versions and execute migrations and seeds -where the version number is > than the current version- will fix that issue.

I will fix it for sure.

**Comment by lorvent** [comment]
thanks :+1:

**Comment by lancepioch** [comment]
You guys seem to be a little unfamiliar with how migrations work. Laravel automatically keeps track of which migrations have and haven't been run yet.

Let's take the following example:

1. Create migrations A, B, C.
2. php artisan migrate will run migrations A, B, C.
3. Create migrations D, E, F.
4. php artisan migrate will run migrations D, E, F.

As long as you correctly create and configure the new migrations, you only need to `php artisan migrate` and all the new ones will be good to go.

**Comment by RachidLaasri** [comment]
I am aware of that, what we were talking about is :

Saying that you created a migration A in release 1.0, in version 1.2 you added a new column and another one in version 1.3, of course the 1.3 update will only have the first column not both because that will generate an error saying the field already exist.

So, people who didn't upgrade to 1.2 and want to directly upgrade to  1.3 they will need to update to 1.2 first and then 1.3.

**Comment by lorvent** [comment]
But he is correct,
we don't need to bother about migrations since laravel will take care of them.

need to bother about other things like seeds, folder permissions (if we need a new writable folder with update for images)

**Comment by lancepioch** [comment]
> Saying that you created a migration A in release 1.0, in version 1.2 you added a new column and another one in version 1.3, of course the 1.3 update will only have the first column not both because that will generate an error saying the field already exist.

It won't give you an error though. Laravel keeps track of all of that. It doesn't matter how many generations of migrations you skip or not.

**Comment by RachidLaasri** [comment]
So, I guess this is enough https://github.com/RachidLaasri/LaravelInstaller/commit/c0d06e0eb52af24a3667f3f1a5be1f5acebe8cd1

**Comment by lorvent** [comment]
yes for migrations thats enough

**Comment by RachidLaasri** [comment]
And it is still executing custom seeds, i believe we are done with this feature if i am corrent?

**Comment by lorvent** [comment]
the same way i explained above?

migrations... laravel keeps a record
but with seeds.... laravel doesn't and if we run a seed accidentally twice.....we will remove all custom data in that table (the way every seed programmed)

also... with every upadate...we may need write access to some folders

**Comment by lancepioch** [comment]
Yes, do not re-run or roll back migrations and do not re-seed the database either.

**Comment by RachidLaasri** [comment]
We are no re-seeding the whole database, just the ones you add in the array.

**Comment by RachidLaasri** [comment]
I will revert to the old way and let Laravel handle the update.

**Comment by hareeshucreate** [comment]
Hi ,

RachidLassri, I have tried to install laravel with this installer,in case of migration it is working fine,but in case of seeding(while i tries to seed my 3 tables, results in class not found). So where i have to implement "composer dump-autoload" before seeding in this package.I have spent 2 days on it.

Thanks,
