### ISSUE TITLE
Checking Web Installer

### ISSUE THREAD

**Issue by renztoygwapo** [RachidLaasri/LaravelInstaller#60]
Hello, Nice Script :)
I am happy to used it. Anyway After I run the script and it run smoothly in laravel 5.3, I realize and suggest that if we run to http://localhost:8000 it will automatically redirect to http://localhost:800/install then after successful installation when I access http://localhost:800/install it goes to 404. Maybe it will just redirect to the root http://localhost:8000. 

 Does it makes sense ? 
 
 Or how can I modify that ?

Thanks

**Comment by alanpilloud** [comment]
In my opinion, a 404 error is ok in this case.
Nobody else than your users should know that it is a valid route.

**Comment by jeremykenedy** [comment]
@renztoygwapo Agree with @alanpilloud . This issue should be closed.
