### ISSUE TITLE
Update route

### ISSUE THREAD

**Issue by alanpilloud** [RachidLaasri/LaravelInstaller#61]
Hello,

What do you think about creating a new route to manage updates ?

If there are migrations that have not been ran, an /update route would be available.
It would redirect to a page in a similar template than the installer and just let the user click a "Update Database" button, and go to a last view with the exit button.

If you're interrested, I'd be glad to add a PR.

**Comment by RachidLaasri** [comment]
Sure! I would love a PR on that.

**Comment by alanpilloud** [comment]
I've make something visible here : 
https://github.com/alanpilloud/LaravelInstaller/tree/dev-update

Would you like to open a new branch in your repo in order to let the community test the update ?

**Comment by alanpilloud** [comment]
PR opened : https://github.com/RachidLaasri/LaravelInstaller/pull/62
