### ISSUE TITLE
canInstall

### ISSUE THREAD

**Issue by markib** [RachidLaasri/LaravelInstaller#65]
ReflectionException in Container.php line 681: Class canInstall does not exist

**Comment by krysennn** [comment]
I'm not sure but i think you using old version of Laravel (under 5.3) and you have no middleware group.

You need to add that in your `app/Http/Kernel.php`:
```
    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \Illuminate\Cookie\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
        ],
    ];
```

**Comment by fsyauqy** [comment]
> You just need to add
> 'canInstall' => \RachidLaasri\LaravelInstaller\Middleware\canInstall::class,
> into $routeMiddleware array in Kernel.php of your app

Based on the answer in #73
