### ISSUE TITLE
Update codebase

### ISSUE THREAD

**Issue by alexcroox** [RachidLaasri/LaravelInstaller#71]
Am I right in assuming this project does not support updating project files which would be a common reason to update the app?

**Comment by RachidLaasri** [comment]
Can you explain more please?

**Comment by alexcroox** [comment]
> Do you want your clients to be able to install a Laravel project just like they do with WordPress or any other CMS? 

When Wordpress updates it also updates it's codebase by downloading and extracting the new files from a .zip, and running database migrations.

**Comment by alexcroox** [comment]
Do you think this is possible with the laravel framework?

**Comment by Chinese1904** [comment]
Anything is possible. You can simply run git pull and have it in sync with your repo.

**Comment by alexcroox** [comment]
The issue being the users who setup my codebase may not have ssh access to be able to run their own commands, which is why I'd use a library like this to begin with

**Comment by Chinese1904** [comment]
You do not need ssh access. Many packages are out there for that use: https://github.com/codedge/laravel-selfupdater
