### ISSUE TITLE
ReflectionException in Container.php line 681: Class canInstall does not exist

### ISSUE THREAD

**Issue by sky9s** [RachidLaasri/LaravelInstaller#73]
Hi~!
An error occurs when executing /install.

Testing : Windows10 / Homestead / laravel5.4

**ReflectionException in Container.php line 681:
Class canInstall does not exist**

1. in Container.php line 681
2. at ReflectionClass->__construct('canInstall') in Container.php line 681
3. at Container->build('canInstall') in Container.php line 565
4. at Container->make('canInstall') in Application.php line 702
5. at Application->make('canInstall') in Pipeline.php line 138
6. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
7. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in SubstituteBindings.php line 41
8. at SubstituteBindings->handle(object(Request), object(Closure)) in Pipeline.php line 148
9. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
10. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
11. at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 148
12. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
13. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
14. at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
15. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
16. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
17. at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
18. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
19. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
20. at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 148
21. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
22. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
23. at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 148
24. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
25. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
26. at Pipeline->then(object(Closure)) in Router.php line 561
27. at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 520
28. at Router->dispatchToRoute(object(Request)) in Router.php line 498
29. at Router->dispatch(object(Request)) in Kernel.php line 174
30. at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 30
31. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
32. at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
33. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
34. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
35. at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
36. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
37. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ValidatePostSize.php line 27
38. at ValidatePostSize->handle(object(Request), object(Closure)) in Pipeline.php line 148
39. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
40. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
41. at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 148
42. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
43. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
44. at Pipeline->then(object(Closure)) in Kernel.php line 149
45. at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 116
46. at Kernel->handle(object(Request)) in index.php line 53

**Comment by HDVinnie** [comment]
i am getting same error. 

Whoops, looks like something went wrong.

1/1
ReflectionException in Container.php line 681:
Class canInstall does not exist

**Comment by HDVinnie** [comment]
any support on this issue?

**Comment by sky9s** [comment]
I think it seems to be a problem due to the version update.
Laravel 5.3 No problem
Problems with laravel 5.4.x (latest version)

I hope this problem will be resolved soon.

**Comment by ririboc** [comment]
After about an hour of researching through the code -- check the Routes.php 

If you comment out the following, the error will go away:

// Route::group(['middleware' => 'canInstall'], function() {
     ...all Installer routes...
// });

**Comment by HDVinnie** [comment]
indeed fixes the error but seems the language is messed up as well.

http://imgur.com/26blFPC

**Comment by l9r** [comment]
You just need to add 
`'canInstall' => \RachidLaasri\LaravelInstaller\Middleware\canInstall::class,`
into $routeMiddleware array in Kernel.php of your app

**Comment by ajayfroiden** [comment]
You can use the forked version for laravel 5.4 https://github.com/Froiden/laravel-installer

**Comment by sky9s** [comment]
Thank you. everybody
