### ISSUE TITLE
Add function to set permission

### ISSUE THREAD

**Issue by rabol** [RachidLaasri/LaravelInstaller#76]
The installer can check the permission, but not set the permission

Please add a feature so that the permissions can be set on the folders

**Comment by RachidLaasri** [comment]
I believe it's better this way, the user should have control over it.

**Comment by tnylea** [comment]
@rabol I think this could be a good feature to add to the config.

Maybe something like:

```
force_file_permissions => true,
```

And if that is set it will try and force the file permissions.

I'll see what I can do to put in a PR for this soon.

**Comment by jeremykenedy** [comment]
Changing those folders permissions may require sudo access and can create security holes in the server. I think this should not handle changing permissions for security reasons. 

While I like the idea very much I think this request should be closed because it introduces security flaws.

**Comment by jeremykenedy** [comment]
@rabol You can always make a shell script and then run it manually as elevated sudo to make this process easier for you. 

Here is an example file you can call `updateperms.sh`:
```
######### Run
updatePermissionsUnix() {
	sudo chgrp -R www-data storage bootstrap/cache
}
updatePermissionsMac() {
	sudo chgrp -R _www storage bootstrap/cache
}

runUpdatePermissions() {
	echo "Attempting to set Unix permissions - www-data read..."
        sudo chmod -R 755 storage/framework/
        sudo chmod -R 755 storage/logs
        sudo chmod -R 755 bootstrap/cache/
	if updatePermissionsUnix; then
		sudo chmod -R ug+rwx storage bootstrap/cache
		echo 'Updated storage access successfully - www-data read allowed.'
		echo $_sep
	else
		echo "Attempt failed - www-data."
		echo $_sep
		echo "Attempting to set Mac permissions - _www read..."
		if updatePermissionsMac; then
			sudo chmod -R ug+rwx storage bootstrap/cache
			echo 'Updated storage access successfully - _www read allowed.'
			echo $_sep
		else
			echo "--- Error updating storage access - www-data failed."
			echo "Updating storage permissions failed - Both www-data and _www."
		    echo $_sep
		    exit 1
		fi
	fi
}
runUpdatePermissions
```

**Comment by akgarg007** [comment]
You can fix this by just running this command in your root terminal

chmod -R ug+rwx storage bootstrap/cache
