### ISSUE TITLE
where is RedirectInstall

### ISSUE THREAD

**Issue by rabol** [RachidLaasri/LaravelInstaller#77]
In the service provider there is a reference to RedirectInstall, but the class is not in the repository
can you add it ?

**Comment by ajayfroiden** [comment]
Change
`"rachidlaasri/laravel-installer": "1.5"`
to 
`"rachidlaasri/laravel-installer": "^1.5"`
 and then do
`composer update`

 You will get the latest version of installer

**Comment by rabol** [comment]
But, the class is not even in the master branch

**Comment by ajayfroiden** [comment]
You can use the forked plugin
[https://github.com/Froiden/LaravelInstaller](https://github.com/Froiden/LaravelInstaller)

**Comment by jeremykenedy** [comment]
Why not merge this fix into this project rather than branch off?

**Comment by RachidLaasri** [comment]
@jeremykenedy He even did change the namespace and replace my name with his. Sad!

**Comment by jeremykenedy** [comment]
Fixed in pull request https://github.com/RachidLaasri/LaravelInstaller/pull/83
