### ISSUE TITLE
NotFoundException

### ISSUE THREAD

**Issue by mms-hamburg** [RachidLaasri/LaravelInstaller#8]
opening http://localhost:8000/install  gives me a
`NotFoundHttpException in Application.php line 879:`

Added the service provider & published the vendor files.

if i look with route:list i can see the installer routes....

any hints?

**Comment by mms-hamburg** [comment]
okay it was the middleware / table checking

**Comment by oleghalin** [comment]
I havent same problem, all was okay, but after one installation this error. What can be?

**Comment by RachidLaasri** [comment]
@oleghalin I replied your issue.
