### ISSUE TITLE
Am getting ReflectionException in installer

### ISSUE THREAD

**Issue by jomonthomaslobo** [RachidLaasri/LaravelInstaller#80]
ReflectionException while tried to install

**Comment by NickRT91** [comment]
I got this too.

**Comment by RachidLaasri** [comment]
Laravel version?

**Comment by thanhminh6996** [comment]
Hi Rachid, can i use it with Laravel 5.4.23 ?

**Comment by RachidLaasri** [comment]
@thanhminh6996 Yes, you can.

**Comment by jomonthomaslobo** [comment]
@RachidLaasri 5.4

**Comment by RachidLaasri** [comment]
Can you post the full error message?

**Comment by jomonthomaslobo** [comment]
I pasted controllers there

**Comment by jeremykenedy** [comment]
Fixed in pull request https://github.com/RachidLaasri/LaravelInstaller/pull/83
