### ISSUE TITLE
php artisan vendor:publish not compiling assets 

### ISSUE THREAD

**Issue by touilahmedimad** [RachidLaasri/LaravelInstaller#81]
after the installation of the package and add the class in the providers , the command php artisan vendor:publish not compile assets , just say Publishing complete.
![problem](https://cloud.githubusercontent.com/assets/11810920/26793158/828cb150-4a0c-11e7-8d39-191127572016.png)

**Comment by RachidLaasri** [comment]
Make sure you added 
```
    RachidLaasri\LaravelInstaller\Providers\LaravelInstallerServiceProvider::class,
```

To your providers.

**Comment by HDVinnie** [comment]
run php artisan cache:clear
then php artisan vendor:publish

**Comment by touilahmedimad** [comment]
i did make sure added the class to the providers and i did run cache:clear

**Comment by jeremykenedy** [comment]
Fixed in pull request https://github.com/RachidLaasri/LaravelInstaller/pull/83
