### ISSUE TITLE
RedirectInstall does not exist

### ISSUE THREAD

**Issue by jbonnett92** [RachidLaasri/LaravelInstaller#82]
Hi,
I followed the instructions and get the following error:
ReflectionException: Class RachidLaasri\LaravelInstaller\Providers\RedirectInstall does not exist.

I installed via ```"rachidlaasri/laravel-installer": "^2.0"```.

Any ideas how to resolve this?

Thanks,
Jamie

**Comment by jeremykenedy** [comment]
Fixed in Pull Request https://github.com/RachidLaasri/LaravelInstaller/pull/83
