### ISSUE TITLE
/install Route not working

### ISSUE THREAD

**Issue by webdesign3r** [RachidLaasri/LaravelInstaller#84]
Hi,

when I setup your package locally, everything works fine, but after uploading to a webserver the /install Route is not working, what am I doing wrong? Isn't this package supposed for uploading the project with ftp and then use the installer to migrate databases etc?

**Comment by RachidLaasri** [comment]
This sounds like a problem with your routing/configs.

Please make sure all of your other routes are working.

**Comment by webdesign3r** [comment]
Do I need to config any routes manually before uploading? When I test the /install on my local computer, its working and opening the installer, so the route is ok, but there is no entry in the web.php file or anything.

Here is what I did:
- Have my laravel 5.4 project
- installed your web installer as said in the readme
- Local test -> OK
- Uploaded project folder to webserver via ftp, including all node_modules folders etc
- try to open mydomain.com/install -> The requested URL /install was not found on this server.

What am I doing wrong?

**Comment by jeremykenedy** [comment]
Is the 404 error a Laravel 404 or nginx 404?

**Comment by robertnicjoo** [comment]
same issue here https://github.com/RachidLaasri/LaravelInstaller/issues/129 Laravel 5.5
