### ISSUE TITLE
The ServiceProvider method does not exist in the loadRoutesFrom class under version 5.3

### ISSUE THREAD

**Issue by AgonyXD** [RachidLaasri/LaravelInstaller#86]
The ServiceProvider method does not exist in the loadRoutesFrom class under version 5.3
require the routes file from within your package service provider's boot method. 
e.g.

> public function boot()
{
    if (! $this->app->routesAreCached()) {
        require __DIR__.'/../../routes.php';
    }
}

**Comment by kmrifat** [comment]
You may face this error only on linux because linux terminal is case sensitive.
To solve this issue 
Go to 
`vendor/rachidlassri/laravel-installer/src/Providers/LaravelInstallerServiceProvider`

and change register 
```
public function register()
    {
        $this->publishFiles();
        $this->loadRoutesFrom(__DIR__.'/../routes/web.php');
    }
```
To 
```
public function register()
    {
        $this->publishFiles();
        $this->loadRoutesFrom(__DIR__.'/../Routes/web.php');
    }
```

**Comment by jeremykenedy** [comment]
I think @kmrifat solved the environment related issue here and this can be closed. @RachidLaasri
